name: Nightly Price Harvest

on:
  schedule:
    - cron: "30 6 * * *"   # 02:30 America/New_York ≈ 06:30 UTC (DST-aware enough for our purposes)
  workflow_dispatch: {}

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg[binary] tenacity python-dotenv pytz

      - name: Run ETL
        env:
          KROGER_CLIENT_ID: ${{ secrets.KROGER_CLIENT_ID }}
          KROGER_CLIENT_SECRET: ${{ secrets.KROGER_CLIENT_SECRET }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL || 'INFO' }}
        run: |
          python -m etl.harvest

